﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace AutoWorldML
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"Gearbox", @"Gearbox")      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Year", @"Year"),new InputOutputColumnPair(@"Power", @"Power"),new InputOutputColumnPair(@"Mileage", @"Mileage")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Url", @"Url"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Make", @"Make"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Model", @"Model"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Eurostandard", @"Eurostandard"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Gearbox",@"Year",@"Power",@"Mileage",@"Url",@"Make",@"Model",@"Eurostandard"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.LbfgsPoissonRegression(l1Regularization:3.04142994795248F,l2Regularization:2.42046427265417F,labelColumnName:@"Price",featureColumnName:@"Features"));

            return pipeline;
        }
    }
}
