
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace AutoWorldML
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel.ModelInput sampleData = new MLModel.ModelInput()
            {
                Url = @"https://www.cars.bg/offer/61ffa6a3959dd44243707933",
                Make = @"Peugeot",
                Model = @"206",
                Year = 2004F,
                Power = 90F,
                Mileage = 206000F,
                Eurostandard = @"EURO 3",
                Gearbox = @"Ръчни скорости",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");


            Console.WriteLine($"Url: {@"https://www.cars.bg/offer/61ffa6a3959dd44243707933"}");
            Console.WriteLine($"Make: {@"Peugeot"}");
            Console.WriteLine($"Model: {@"206"}");
            Console.WriteLine($"Year: {2004F}");
            Console.WriteLine($"Power: {90F}");
            Console.WriteLine($"Mileage: {206000F}");
            Console.WriteLine($"Eurostandard: {@"EURO 3"}");
            Console.WriteLine($"Gearbox: {@"Ръчни скорости"}");
            Console.WriteLine($"Price: {2500F}");


            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
